site_name: Scratch作品分级协议
repo_url: https://github.com/HydroGest/SPGA/
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences